name: First Example

on: push

jobs:
    first_job:
        runs-on: [self-hosted, Linux, X64]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List and Readfile
              run: |
                  echo "My First Github action job"
                  ls -ltra
                  cat Readme.md

            - name: Generate ASCII artwork
              run: cowsay -f dragon "I'm a dreagon " >> dragon.txt

            # - name: List Files
            #   run: 

            # - name: Read File
            #   run: cat Readme.md
    
